### ISSUE TITLE
 Cannot find name for type 'elastix_resampled_to_auto'!

### ISSUE THREAD

**Issue by EPNSED** [ChristophKirst/ClearMap2#102]
Good day!! I'm following ClearMap tutorial and getting the following error.  I installed Clearmap from conda as well as from the source, both produce the same error.  Please help resolve this.
```
>>> align_channels_parameter = {
...     "moving_image" : ws.filename('resampled', postfix='autofluorescence'),
...     "fixed_image"  : ws.filename('resampled'),
... "affine_parameter_file"  : align_channels_affine_file,
...     "bspline_parameter_file" : None,
... "result_directory" :  ws.filename('elastix_resampled_to_auto')
...     };
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/userapp/Clearmap2-v1.2/ClearMap2/ClearMap/IO/Workspace.py", line 286, in filename
    debug=debug, **kwargs);
  File "/userapp/Clearmap2-v1.2/ClearMap2/ClearMap/IO/Workspace.py", line 152, in filename
    raise ValueError('Cannot find name for type %r!' % ftype);
ValueError: Cannot find name for type 'elastix_resampled_to_auto'!

```

**Comment by Hesham3esa** [comment]
i know this one, 

dont use spaces in file names at all. instead use "_" and it will work!

**Comment by Mechanic707** [comment]
> Good day!! I'm following ClearMap tutorial and getting the following error. I installed Clearmap from conda as well as from the source, both produce the same error. Please help resolve this.
> 
> ```
> >>> align_channels_parameter = {
> ...     "moving_image" : ws.filename('resampled', postfix='autofluorescence'),
> ...     "fixed_image"  : ws.filename('resampled'),
> ... "affine_parameter_file"  : align_channels_affine_file,
> ...     "bspline_parameter_file" : None,
> ... "result_directory" :  ws.filename('elastix_resampled_to_auto')
> ...     };
> Traceback (most recent call last):
>   File "<stdin>", line 6, in <module>
>   File "/userapp/Clearmap2-v1.2/ClearMap2/ClearMap/IO/Workspace.py", line 286, in filename
>     debug=debug, **kwargs);
>   File "/userapp/Clearmap2-v1.2/ClearMap2/ClearMap/IO/Workspace.py", line 152, in filename
>     raise ValueError('Cannot find name for type %r!' % ftype);
> ValueError: Cannot find name for type 'elastix_resampled_to_auto'!
> ```

Hello！ Have you solved the problem？ I had the same problem and tried some methods, but it didn't seem to work.

**Comment by Hesham3esa** [comment]
Yes, please dont put spaces in your folder name. And you should be fine. Eazybeazy


Sent from Yahoo Mail for iPhone


On Saturday, November 18, 2023, 5:49 AM, Mechanic707 ***@***.***> wrote:





Good day!! I'm following ClearMap tutorial and getting the following error. I installed Clearmap from conda as well as from the source, both produce the same error. Please help resolve this.
>>> align_channels_parameter = {
...     "moving_image" : ws.filename('resampled', postfix='autofluorescence'),
...     "fixed_image"  : ws.filename('resampled'),
... "affine_parameter_file"  : align_channels_affine_file,
...     "bspline_parameter_file" : None,
... "result_directory" :  ws.filename('elastix_resampled_to_auto')
...     };
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
  File "/userapp/Clearmap2-v1.2/ClearMap2/ClearMap/IO/Workspace.py", line 286, in filename
    debug=debug, **kwargs);
  File "/userapp/Clearmap2-v1.2/ClearMap2/ClearMap/IO/Workspace.py", line 152, in filename
    raise ValueError('Cannot find name for type %r!' % ftype);
ValueError: Cannot find name for type 'elastix_resampled_to_auto'!


Hello！ Have you solved the problem？ I had the same problem and tried some methods, but it didn't seem to work.
