### ISSUE TITLE
TubeMap: "IndexError: list index out of range" while runnin the cell of Rigid z-alignment

### ISSUE THREAD

**Issue by jeng87** [ChristophKirst/ClearMap2#105]
runcell('Rigid z-alignment', '/home/ClearMap2/Documentation/Example/TubeMap/TubeMap_test.py')
Traceback (most recent call last):

  File "/home/ClearMap2/Documentation/Example/TubeMap/TubeMap_test.py", line 103, in <module>
    layout = stw.WobblyLayout(expression=ws.filename('raw'), tile_axes=['X','Y'], overlaps=(45, 155));

  File "/home/ClearMap2/ClearMap/Alignment/Stitching/StitchingWobbly.py", line 725, in __init__
    strg.TiledLayout.__init__(self, sources = sources, expression = expression, tile_axes = tile_axes, tile_shape = tile_shape, tile_positions = tile_positions, positions = positions, overlaps = overlaps, alignments = alignments, position = position, shape = shape, dtype = dtype, order = order);

  File "/home/ClearMap2/ClearMap/Alignment/Stitching/StitchingRigid.py", line 1923, in __init__
    self.update_sources_from_alignments();

  File "/home/ClearMap2/ClearMap/Alignment/Stitching/StitchingRigid.py", line 1328, in update_sources_from_alignments
    positions = positions_from_tree(sources = self.sources, alignments = self.alignments, fixed_source=self.sources[0]);

  File "/home/ClearMap2/ClearMap/Alignment/Stitching/StitchingRigid.py", line 3714, in positions_from_tree
    ndim = alignments[0].ndim

IndexError: list index out of range

**Comment by jeng87** [comment]
This problem has been fixed.

Regarding to the specific cell of Rigid z-alignment to be ran in TubeMap. Check the inputting image files of **expression_raw** and **expression_arteries** which have to be adjacent to each other. In the other words, this cell is about to align 2 tiles in the same depth or same Z axis. Therefore, the **expression_raw** should contain files include vessel related tile_1 and tile_2, and its same to the inputting of **expression_arteries** with arteries of tile_1 and tile_2. Again, these two tiles need to be adjacent to each other.
