### ISSUE TITLE
.sh install meet some error

### ISSUE THREAD

**Issue by qweasdf1354** [ChristophKirst/ClearMap2#129]
Hi author, i wanna to seek your help
when i install the clearmap2 using the  install_gui.sh, i meet 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/z/ClearMap2/ClearMap/Utils/install_utils.py", line 224, in patch_env
    env_mgr = EnvFileManager(cfg_path, dest_path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/z/ClearMap2/ClearMap/Utils/install_utils.py", line 29, in __init__
    with open(self.cfg_path, 'r') as in_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/home/z/ClearMap2/'

Could you help me?

**Comment by qweasdf1354** [comment]
and i just wanna to ask if i install the ClearMapUi39.yml already, do i need to perform the .sh? and how can i activate the gui

**Comment by Tas-V** [comment]
Hi,

What I did was

./install_gui.sh -f ClearMapUi39.yml 

In the bash terminal while in the ClearMap2.1 directory. This installs and creates the ClearMapUi39 environment correctly.

After responding yes to everything when prompted, close the terminal, reopen, activate the ClearMapUi39 env, and then type clearmap-ui to launch the GUI.

**Comment by crousseau** [comment]
@Tas-V That is indeed the way to go. Please let me know if you have comments on the installer.
@qweasdf1354, does the issue persist with the above solution

**Comment by Tas-V** [comment]
@crousseau Everything seems fine with the installer; I had to change the numpy version to 1.24.4 due to an error message in my fork but am unsure if that would be necessary for the main branch.

**Comment by qweasdf1354** [comment]
Thanks a lot for your reply!! i will try it soon

**Comment by KHBHH** [comment]
Hi all, 

I was having similar issue as well, but I used the above command so that the installation starts: 

./install_gui.sh -f ClearMapUi39.yml

But now I am getting error as such: 
                                                                                                                                  
**Updating CUDA dependencies for ClearMap                                                                                                      
  Creating temporary environment                                                                                                             
usage: conda [-h] [-v] [--no-plugins] [-V] COMMAND ...
conda: error: unrecognized arguments: --experimental-solver=libmamba**

Any idea what might be the issue?

**Comment by crousseau** [comment]
@KHBHH

It seems there are some recent changes in conda making this incompatible. You can try replacing
`--experimental-solver=libmamba`
in the install_gui.sh script
with
`--solver=libmamba`

Please let me know if this works
