### ISSUE TITLE
Traceback error when loading UI

### ISSUE THREAD

**Issue by Stuff25** [ChristophKirst/ClearMap2#136]
Hello,

I installed the UI on a Linux VirtualBox, but when I ran "clearmap-ui", it started to load then I got this long error:

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Traceback (most recent call last):
  File "messagestream.pyx", line 91, in scipy._lib.messagestream.MessageStream.close
OSError: [Errno 26] Text file busy: b'/media/sf_Rat_Brain_Slabs/TempTutorial/scipy-jueicqb_'
Exception ignored in: 'scipy._lib.messagestream.MessageStream.__dealloc__'
Traceback (most recent call last):
  File "messagestream.pyx", line 91, in scipy._lib.messagestream.MessageStream.close
OSError: [Errno 26] Text file busy: b'/media/sf_Rat_Brain_Slabs/TempTutorial/scipy-jueicqb_'
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/ClearMapUi39/bin/clearmap-ui", line 33, in <module>
    sys.exit(load_entry_point('ClearMap2==2.1.0', 'gui_scripts', 'clearmap-ui')())
  File "/home/user/anaconda3/envs/ClearMapUi39/bin/clearmap-ui", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/site-packages/ClearMap2-2.1.0-py3.9-linux-x86_64.egg/ClearMap/gui/run_gui.py", line 89, in <module>
    from ClearMap.gui.widgets import OrthoViewer, ProgressWatcher, setup_mini_brain, StructureSelector, \
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/site-packages/ClearMap2-2.1.0-py3.9-linux-x86_64.egg/ClearMap/gui/widgets.py", line 22, in <module>
    from skimage import transform as sk_transform  # WARNING: Slowish import, should be replaced
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/site-packages/skimage/_shared/lazy.py", line 62, in __getattr__
    return importlib.import_module(f'{package_name}.{name}')
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/site-packages/skimage/transform/__init__.py", line 4, in <module>
    from .radon_transform import (radon, iradon, iradon_sart,
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/site-packages/skimage/transform/radon_transform.py", line 6, in <module>
    from ._warps import warp
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/site-packages/skimage/transform/_warps.py", line 9, in <module>
    from ..measure import block_reduce
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/site-packages/skimage/measure/__init__.py", line 6, in <module>
    from ._polygon import approximate_polygon, subdivide_polygon
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/site-packages/skimage/measure/_polygon.py", line 2, in <module>
    from scipy import signal
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/site-packages/scipy/__init__.py", line 134, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/site-packages/scipy/signal/__init__.py", line 338, in <module>
    from ._peak_finding import *
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/site-packages/scipy/signal/_peak_finding.py", line 8, in <module>
    from scipy.stats import scoreatpercentile
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/site-packages/scipy/stats/__init__.py", line 623, in <module>
    from ._rvs_sampling import rvs_ratio_uniforms
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/site-packages/scipy/stats/_rvs_sampling.py", line 2, in <module>
    from scipy.stats.sampling import RatioUniforms
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/site-packages/scipy/stats/sampling.py", line 59, in <module>
    from ._sampling import FastGeneratorInversion, RatioUniforms  # noqa: F401
  File "/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/site-packages/scipy/stats/_sampling.py", line 8, in <module>
    from ._unuran.unuran_wrapper import NumericalInversePolynomial
  File "unuran_wrapper.pyx", line 188, in init scipy.stats._unuran.unuran_wrapper
  File "unuran_wrapper.pyx", line 167, in scipy.stats._unuran.unuran_wrapper._setup_unuran
  File "messagestream.pyx", line 33, in scipy._lib.messagestream.MessageStream.__cinit__
OSError: [Errno 26] Text file busy: b'/media/sf_Rat_Brain_Slabs/TempTutorial/scipy-jueicqb_'
/home/user/anaconda3/envs/ClearMapUi39/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py:181: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn(
free(): invalid pointer
Aborted (core dumped)
```

I managed to run the UI on a previous virtual machine but I moved to a new one to increase the RAM directed at the VM, since the program kept crashing on the old one. I feel like I followed all the same steps so I'm not sure why it broke this time. Any help us appreciated, thanks.

**Comment by whygrossman** [comment]
I don't remember the specifics, but I had seen something about multiple environments accessing the same scipy slowing down and crashing guis.

**Comment by crousseau** [comment]
Hi, can  you try with 3.1 ? It's currently in beta but should already be usable.
